# VS Code Development Dockerfile for CRG Container
# Base image
FROM python:3.11-slim-buster
# Set the working directory
WORKDIR /workspaces/crg-data

# Update OS package list, install packages, and clear apt cache
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install --no-install-recommends -y git ssh && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copy the Python pip requirements file
COPY _requirements/requirements_dev.txt _requirements/requirements_dev.txt

# Upgrade pip and install requirements from the requirements file
RUN python -m pip install --no-cache-dir --upgrade pip && \
    python -m pip install --no-cache-dir -r _requirements/requirements_dev.txt && \
    rm -rf _requirements

# Set the PYTHONPATH environment variable
ENV PYTHONPATH=/workspaces/crg-data

# Start the bash prompt
CMD ["/bin/bash"]
